apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-server-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: dms-server
  template:
    metadata:
      labels:
        app: dms-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dms-server
        image: dnjsakf/dms-server:1.0.9-dev
        ports:
        - containerPort: 3000
        env:
          - name: REDIS_URL
            valueFrom:
              configMapKeyRef:
                name: dms-app-config
                key: REDIS_URL
          - name: DB_POSTGRES_HOST
            valueFrom:
              configMapKeyRef:
                name: dms-app-config
                key: DB_POSTGRES_PORT
