apiVersion: v1
kind: Service
metadata:
  name: dms-server-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dms-server
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 3000