apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-server-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dms-server
  template:
    metadata:
      labels:
        app: dms-server
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dms-server
        image: dnjsakf/dms-server:1.0.8-dev
        ports:
        - containerPort: 3000
        env:
          - name: EXPRESS_HOST
            value: localhost
          - name: EXPRESS_PORT
            value: "3000"
          - name: REDIS_URL
            # value: "redis://redis-service.default.svc.cluster.local:6379"
            value: "redis://192.168.0.61:6379"
          - name: DB_POSTGRES_HOST
            # value: "postgres-service.default.svc.cluster.local"
            value: "192.168.0.61"
          - name: DB_POSTGRES_PORT
            value: "5432"
        