apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: default
spec:
  type: ExternalName
  externalName: dev.dms-app.com
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
