apiVersion: v1
kind: Service
metadata:
  name: demo-app-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-app
  ports:
  - name: http
    protocol: TCP
    port: 4080
    targetPort: 8080
