apiVersion: v1
kind: Service
metadata:
  name: demo-app
  labels:
    app: demo-app
  namespace: default
spec:
  type: NodePort
  selector:
    app.kubernetes.io/name: argocd-server
  sessionAffinity: None
  ports:
  - name: http
    nodePort: 38080
    port: 80
    protocol: TCP
    targetPort: 8080
  - name: https
    nodePort: 38443
    port: 443
    protocol: TCP
    targetPort: 8080
