apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: demo-app
  finalizers: []
spec:
  destination:
    name: ''
    namespace: default
    server: https://kubernetes.default.svc
  source:
    path: demo-app
    repoURL: https://github.com/dnjsakf/argocd-apps.git
    targetRevision: HEAD
  sources: []
  project: default
  syncPolicy:
    syncOptions:
      - PrunePropagationPolicy=foreground
