apiVersion: v1
kind: Service
metadata:
  name: demo-manage-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-manage-api
  ports:
  - name: http
    protocol: TCP
    port: 81
    targetPort: 9092
