apiVersion: v1
kind: Service
metadata:
  name: demo-user-api-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: demo-user-api
  ports:
  - name: http
    protocol: TCP
    port: 82
    targetPort: 9092
