apiVersion: apps/v1
kind: Deployment
metadata:
  name: dms-client-deploy
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: dms-client
  template:
    metadata:
      labels:
        app: dms-client
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: dms-client
        image: dnjsakf/dms-client:1.0.28-dev
        ports:
        - containerPort: 80
        env:
        - name: NEXT_PUBLIC_API_BASE_URL
          value: "http://localhost:8080/api"
