apiVersion: v1
kind: Service
metadata:
  name: dms-client-service
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: dms-client
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 80
